apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: regcred

      containers:
        - name: backend
          image: 500204/devopsbackend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
      
